openapi: 3.0.1
info:
  title: this is a title
  description: this is a description
tags:
  - name: Tag A
    description: cake
    x-hack: true
  - name: Tag B
    description: coffee
    x-code: hack